Overview of this week's notebook:

- use pandas to read a csv file
- learn how to delete rows

In [1]:
import pandas as pd

In [2]:
# load a data file
# note the relative filepath! where is this file located?
# note the dtype argument! always specify that fips codes are strings, otherwise pandas guesses int
# df = pd.read_csv('data/social_explorer.csv', dtype={'GEOID10':str})
df = pd.read_csv('data/social_explorer.csv')

In [3]:
df.shape

(2347, 102)

In [4]:
df.head()

,FIPS,Geographic Identifier,Name of Area,Qualifying Name,State/U.S.-Abbreviation (USPS),Summary Level,Geographic Component,File Identification,Logical Record Number,US,...,Median Household Income (In 2018 Inflation Adjusted Dollars),Housing Units,Occupied Housing Units:,Occupied Housing Units: Owner Occupied,Occupied Housing Units: Renter Occupied,Population for Whom Poverty Status Is Determined:,Population for Whom Poverty Status Is Determined: Under 1.00 (Doing Poorly),Population for Whom Poverty Status Is Determined: 1.00 to 1.99 (Struggling),Population for Whom Poverty Status Is Determined: Under 2.00 (Poor or Struggling),Population for Whom Poverty Status Is Determined: 2.00 and Over (Doing Ok)
0,Geo_FIPS,Geo_GEOID,Geo_NAME,Geo_QName,Geo_STUSAB,Geo_SUMLEV,Geo_GEOCOMP,Geo_FILEID,Geo_LOGRECNO,Geo_US,...,SE_A14006_001,SE_A10001_001,SE_A10060_001,SE_A10060_002,SE_A10060_003,SE_B13004_001,SE_B13004_002,SE_B13004_003,SE_B13004_004,SE_B13004_005
1,06037101110,14000US06037101110,Census Tract 1011.10,"Census Tract 1011.10, Los Angeles County, Cali...",ca,140,00,ACSSF,0003870,NaN,...,53077,1743,1596,767,829,4207,679,916,1595,2612
2,06037101122,14000US06037101122,Census Tract 1011.22,"Census Tract 1011.22, Los Angeles County, Cali...",ca,140,00,ACSSF,0003871,NaN,...,88953,1391,1256,1026,230,3234,109,152,261,2973
3,06037101210,14000US06037101210,Census Tract 1012.10,"Census Tract 1012.10, Los Angeles County, Cali...",ca,140,00,ACSSF,0003872,NaN,...,32119,2402,2321,337,1984,6042,1994,1657,3651,2391
4,06037101220,14000US06037101220,Census Tract 1012.20,"Census Tract 1012.20, Los Angeles County, Cali...",ca,140,00,ACSSF,0003873,NaN,...,41728,1328,1294,471,823,3497,524,1159,1683,1814

In [7]:
# I want to see all the data
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [8]:
# look at the data types
df.dtypes

FIPS                                                                                   object
Geographic Identifier                                                                  object
Name of Area                                                                           object
Qualifying Name                                                                        object
State/U.S.-Abbreviation (USPS)                                                         object
Summary Level                                                                          object
Geographic Component                                                                   object
File Identification                                                                    object
Logical Record Number                                                                  object
US                                                                                     object
Region                                                                                 object
Division                                                                               object
State (Census Code)                                                                    object
State (FIPS)                                                                           object
County                                                                                 object
County Subdivision (FIPS)                                                              object
Place (FIPS Code)                                                                      object
Place (State FIPS + Place FIPS)                                                        object
Census Tract                                                                           object
Block Group                                                                            object
Consolidated City                                                                      object
American Indian Area/Alaska Native Area/Hawaiian Home Land (Census)                    object
American Indian Area/Alaska Native Area/Hawaiian Home Land (FIPS)                      object
American Indian Trust Land/Hawaiian Home Land Indicator                                object
American Indian Tribal Subdivision (Census)                                            object
American Indian Tribal Subdivision (FIPS)                                              object
Alaska Native Regional Corporation (FIPS)                                              object
Metropolitan and Micropolitan Statistical Area                                         object
Combined Statistical Area                                                              object
Metropolitan Division                                                                  object
Metropolitan Area Central City                                                         object
Metropolitan/Micropolitan Indicator Flag                                               object
New England City and Town Combined Statistical Area                                    object
New England City and Town Area                                                         object
New England City and Town Area Division                                                object
Urban Area                                                                             object
Urban Area Central Place                                                               object
Current Congressional District ***                                                     object
State Legislative District Upper                                                       object
State Legislative District Lower                                                       object
Voting District                                                                        object
ZIP Code Tabulation Area (3-digit)                                                     object
ZIP Code Tabulation Area (5-digit)                                                     object
Subbarrio (FIPS)                                                                       object
School District (Elementary)                                                           object
School District (Secondary)                                                            object
School District (Unified)                                                              object
Urban/Rural                                                                            object
Principal City Indicator                                                               object
Traffic Analysis Zone                                                                  object
Urban Growth Area                                                                      object
Tribal Tract                                                                           object
Tribal Block Group                                                                     object
Public Use Microdata Area - 5% File                                                    object
Public Use Microdata Area - 1% File                                                    object
Total Population                                                                       object
Total Population.1                                                                     object
Population Density (Per Sq. Mile)                                                      object
Area (Land)                                                                            object
Total Population:                                                                      object
Total Population: Male                                                                 object
Total Population: Female                                                               object
Total Population:.1                                                                    object
Total Population: Under 5 Years                                                        object
Total Population: 5 to 9 Years                                                         object
Total Population: 10 to 14 Years                                                       object
Total Population: 15 to 17 Years                                                       object
Total Population: 18 to 24 Years                                                       object
Total Population: 25 to 34 Years                                                       object
Total Population: 35 to 44 Years                                                       object
Total Population: 45 to 54 Years                                                       object
Total Population: 55 to 64 Years                                                       object
Total Population: 65 to 74 Years                                                       object
Total Population: 75 to 84 Years                                                       object
Total Population: 85 Years and Over                                                    object
Total Population:.2                                                                    object
Total Population: White Alone                                                          object
Total Population: Black or African American Alone                                      object
Total Population: American Indian and Alaska Native Alone                              object
Total Population: Asian Alone                                                          object
Total Population: Native Hawaiian and Other Pacific Islander Alone                     object
Total Population: Some Other Race Alone                                                object
Total Population: Two or More Races                                                    object
Households:                                                                            object
Households: Family Households                                                          object
Households: Family Households: Married-Couple Family                                   object
Households: Family Households: Other Family                                            object
Households: Family Households: Other Family: Male Householder, No Wife Present         object
Households: Family Households: Other Family: Female Householder, No Husband Present    object
Households: Nonfamily Households                                                       object
Households: Nonfamily Households: Male Householder                                     object
Households: Nonfamily Households: Female Householder                                   object
Median Household Income (In 2018 Inflation Adjusted Dollars)                           object
Housing Units                                                                          object
Occupied Housing Units:                                                                object
Occupied Housing Units: Owner Occupied                                                 object
Occupied Housing Units: Renter Occupied                                                object
Population for Whom Poverty Status Is Determined:                                      object
Population for Whom Poverty Status Is Determined: Under 1.00 (Doing Poorly)            object
Population for Whom Poverty Status Is Determined: 1.00 to 1.99 (Struggling)            object
Population for Whom Poverty Status Is Determined: Under 2.00 (Poor or Struggling)      object
Population for Whom Poverty Status Is Determined: 2.00 and Over (Doing Ok)             object
dtype: object

oops! That first row is not a data row. Let's get rid of it.

Determine which row you want to drop by its index number. In this case, it is `[0]`.

In [5]:
df.drop([0])

,FIPS,Geographic Identifier,Name of Area,Qualifying Name,State/U.S.-Abbreviation (USPS),Summary Level,Geographic Component,File Identification,Logical Record Number,US,...,Median Household Income (In 2018 Inflation Adjusted Dollars),Housing Units,Occupied Housing Units:,Occupied Housing Units: Owner Occupied,Occupied Housing Units: Renter Occupied,Population for Whom Poverty Status Is Determined:,Population for Whom Poverty Status Is Determined: Under 1.00 (Doing Poorly),Population for Whom Poverty Status Is Determined: 1.00 to 1.99 (Struggling),Population for Whom Poverty Status Is Determined: Under 2.00 (Poor or Struggling),Population for Whom Poverty Status Is Determined: 2.00 and Over (Doing Ok)
1,06037101110,14000US06037101110,Census Tract 1011.10,"Census Tract 1011.10, Los Angeles County, Cali...",ca,140,00,ACSSF,0003870,NaN,...,53077,1743,1596,767,829,4207,679,916,1595,2612
2,06037101122,14000US06037101122,Census Tract 1011.22,"Census Tract 1011.22, Los Angeles County, Cali...",ca,140,00,ACSSF,0003871,NaN,...,88953,1391,1256,1026,230,3234,109,152,261,2973
3,06037101210,14000US06037101210,Census Tract 1012.10,"Census Tract 1012.10, Los Angeles County, Cali...",ca,140,00,ACSSF,0003872,NaN,...,32119,2402,2321,337,1984,6042,1994,1657,3651,2391
4,06037101220,14000US06037101220,Census Tract 1012.20,"Census Tract 1012.20, Los Angeles County, Cali...",ca,140,00,ACSSF,0003873,NaN,...,41728,1328,1294,471,823,3497,524,1159,1683,1814
5,06037101300,14000US06037101300,Census Tract 1013,"Census Tract 1013, Los Angeles County, California",ca,140,00,ACSSF,0003874,NaN,...,86914,1584,1435,1268,167,4250,391,534,925,3325
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2342,06037980031,14000US06037980031,Census Tract 9800.31,"Census Tract 9800.31, Los Angeles County, Cali...",ca,140,00,ACSSF,0006211,NaN,...,64500,24,24,0,24,48,0,0,0,48
2343,06037980033,14000US06037980033,Census Tract 9800.33,"Census Tract 9800.33, Los Angeles County, Cali...",ca,140,00,ACSSF,0006212,NaN,...,NaN,14,14,0,14,14,14,0,14,0
2344,06037990100,14000US06037990100,Census Tract 9901,"Census Tract 9901, Los Angeles County, California",ca,140,00,ACSSF,0006213,NaN,...,NaN,0,0,0,0,0,0,0,0,0
2345,06037990200,14000US06037990200,Census Tract 9902,"Census Tract 9902, Los Angeles County, California",ca,140,00,ACSSF,0006214,NaN,...,NaN,0,0,0,0,0,0,0,0,0
2346,06037990300,14000US06037990300,Census Tract 9903,"Census Tract 9903, Los Angeles County, California",ca,140,00,ACSSF,0006215,NaN,...,NaN,0,0,0,0,0,0,0,0,0

or... we can re-import the data skipping the second row. This is better. Why?

In [ ]:
df = pd.read_csv('data/social_explorer.csv',skiprows=[1])

In [ ]:
df.head()

Waaaaaiiit... what happened to the "0" in the FIPS code?

That's right, python interprets this as a integer columns, and crops the leading zeroes. Let's fix this by re-re-importing the data, specifying the FIPS column as a string:

In [ ]:
df = pd.read_csv('data/social_explorer.csv',
                 skiprows=[1],
                dtype={'FIPS':str})

In [ ]:
df.head()

In [ ]:
df.dtypes

In [ ]:
df.tail()

In [ ]:
df.sample(5)

In [ ]:
df.columns

This is what data usually looks like... unwieldly...

In [ ]:
list(df)

In [ ]:
# how many records in each column that are not null?
df.value_counts()

In [ ]:
# data types of the columns
df.dtypes